---
title: "Clases Latentes Renca"
author: "Cristóbal Ortiz"
output: html_document
date: "2023-07-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	fig.align = "left",
	fig.topcaption = TRUE,
	message = FALSE,
	warning = FALSE,
	cache = FALSE
)
Sys.setlocale("LC_ALL","ES_ES.UTF-8")
```

```{r packages, message=FALSE, warning=FALSE, include=FALSE}
library(poLCA)
library(knitr)
library(kableExtra)
library(gridExtra)
library(tidyverse)
library(sjmisc)
library(sjlabelled)
library(ggrepel)
library(ggalluvial)
library(haven)
```

```{r datos}
remove(list = ls())
renca <- read_dta("../input/data/Renca_1010_macrozona.dta")
#renca_1 <- read_dta("../input/data/Renca_320_unidadbarrial.dta")
#load("../input/data/elsoc.sub.Rdata")
```

```{r recode}
#remove(renca_cs)

renca_cs <- renca %>% 
  select(respondent_id, 
         q0027, #futuro de renca
         starts_with("q0007_"), #confianza en autoridades e instituciones comunales
         starts_with("q0009_"), -q0009_0017, -q0009_0018, -q0009_0019, -q0009_other, #participación 
         starts_with("q0011_"),  #actividad cívica
         q0027)

#subset participacion
renca_part <- renca %>% 
  select(respondent_id, 
         starts_with("q0009_"), -q0009_0016, -q0009_0017, -q0009_0018, -q0009_0019, -q0009_other,) %>% 
  mutate(part = rowSums(across(where(is.numeric)), na.rm = T)) %>% 
  select(respondent_id, part)

#subset activida cívica
renca_actv <- renca %>% 
  select(respondent_id, 
         starts_with("q0011_")) 

renca_actv[renca_actv == 2] <- 0
renca_actv[renca_actv == 3] <- NA
renca_actv[renca_actv == 4] <- NA

renca_actv <- renca_actv%>% 
  mutate(actv = rowSums(across(where(is.numeric)), na.rm = T)) %>% 
  select(respondent_id, actv)

#join subsets
renca_cs <- renca_cs %>% 
  left_join(renca_part, by = 'respondent_id') %>% 
  left_join(renca_actv, by = 'respondent_id')

renca_cs[renca_cs == 6] <- NA
renca_cs[renca_cs == 7] <- NA
renca_cs[renca_cs == 98] <- NA
renca_cs[renca_cs == 99] <- NA

renca_cs$q0027[renca_cs$q0027 == 4] <- NA
renca_cs$q0027[renca_cs$q0027 == 5] <- NA

renca_cs <- renca_cs %>% 
  mutate(futur = car::recode(q0027, "c(3,2)=1; c(1)=2"),
         confa = (q0007_0001 + q0007_0002 + q0007_0007)/3,
         confat = cut(confa, breaks = c(0,3.5,5), labels = c(1,2)),
         confi = (q0007_0003 + q0007_0004 + q0007_0005 + q0007_0006)/4,
         confit = cut(confa, breaks = c(0,3.5,5), labels = c(1,2)),
         parti = car::recode(part, "c(0)=1; c(1,2,3,4,5)=2"),
         activi = car::recode(actv, "c(0)=1; c(1,2,3,4,5)=2")) %>% 
  set_labels(futur, labels = c("Pesimista", "Optimista")) %>% 
  set_labels(confat, labels = c("No confía (autoridades)","Confía (autoridades)")) %>% 
  set_labels(confit, labels = c("No confía (instituciones)", "No confía (instituciones)")) %>% 
  set_labels(parti, labels = c("No participa","Participa")) %>% 
  set_labels(activi, labels = c("Inactivo","Activo")) %>% 
  as_numeric(futur, confat, confit, parti, activi) 

renca_cs_lca <- renca_cs %>% 
  select(respondent_id, futur, confat, confit, parti, activi) %>% 
  drop_na()

#frq(renca_cs_lca)
  
```

```{r modelo-lca}
set.seed(1)

var <- cbind(futur, confat, confit, parti, activi) ~ 1

# Tres clases --------------------------------------------------------------------------
#tipos_3 <- poLCA(var, renca_cs_lca, nclass = 3, na.rm = TRUE, maxiter = 5000, nrep = 10)

#renca_cs_lca$clase_3 <- as.factor(tipos_3$predclass)

#tabla_3 <- table(renca_cs_lca$clase_3)
#prop.table(tabla_3)

# Cuatro clases ------------------------------------------------------------------------
tipos_4 <- poLCA(var, renca_cs_lca, nclass = 4, na.rm = TRUE, maxiter = 5000, nrep = 10)

renca_cs_lca$clase_4 <- as.factor(tipos_4$predclass)

tabla_4 <- table(renca_cs_lca$clase_4)
prop.table(tabla_4)

# Cinco clases  ------------------------------------------------------------------------
#tipos_5 <- poLCA(var, renca_cs_lca, nclass = 5, na.rm = TRUE, maxiter = 5000, nrep = 10)

#renca_cs_lca$clase_5 <- as.factor(tipos_5$predclass)

#tabla_5 <- table(renca_cs_lca$clase_5)
#prop.table(tabla_5)
```

```{r cuatro-clases}
remove(tab_4_cs)
tab1_4 <- renca_cs_lca %>% group_by(clase_4, futur) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 1) %>% rename(Clase=clase_4, Tipos=futur)

tab2_4 <- renca_cs_lca %>% group_by(clase_4, confat) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 2) %>% rename(Clase=clase_4, Tipos=confat)

tab3_4 <- renca_cs_lca %>% group_by(clase_4, confit) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 3) %>% rename(Clase=clase_4, Tipos=confit)

tab4_4 <- renca_cs_lca %>% group_by(clase_4, parti) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 4) %>% rename(Clase=clase_4, Tipos=parti)

tab5_4 <- renca_cs_lca %>% group_by(clase_4, activi) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 5) %>% rename(Clase=clase_4, Tipos=activi)

tab_4_cs <- rbind(tab1_4, tab2_4, tab3_4, tab4_4, tab5_4)
rm(tab1_4, tab2_4, tab3_4, tab4_4, tab5_4)

tab_4_cs <- tab_4_cs %>% 
  mutate(Clase = factor(Clase, levels = c(2,4,1,3), labels = c("Altamente\ncohesionados (07.25%)", 
                                                               "Confiados\nno participativos (03.62%)", 
                                                               "Participativos\ndesconfiados (21.65%)",
                                                               "Poco\ncohesionados (67.46%)")),
         Tipos  = factor(Tipos, levels = c(1,2), labels = c("No presenta", "Presenta")),
         var  = factor(var, levels = c(1,2,3,4,5), labels = c("Proyección futuro",
                                                              "Confianza (autoridades)",
                                                              "Confianza (instituciones)",
                                                              "Participación organizaciones",
                                                              "Actividad cívica")))

tab_4_cs %>% ggplot(aes(x = freq, y = fct_rev(factor(var)),  fill = fct_rev(Tipos))) + 
  geom_bar(stat = 'identity', position = 'stack') +
  labs(y = NULL, x = NULL,
       title = "Perfiles de cohesión social: 4 clases", fill = "") +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 5), labels = scales::percent, limits=c(0, 1)) +
  theme_bw() + 
  scale_fill_viridis_d(end = .85, option = 'viridis') +
  theme(axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank()) +
  facet_grid(~ Clase) +
  guides(fill = guide_legend(reverse = TRUE))

#ggsave(filename = "../output/4_clases_cs.jpg", width = 35, height = 15, units = "cm")
```

```{r save-dataset}
renca_cs_lca <- renca_cs_lca %>% 
  mutate(class_4 = factor(clase_4, levels = c(2,4,1,3), labels = c("Altamente\ncohesionados (07.25%)", 
                                                               "Confiados\nno participativos (03.62%)", 
                                                               "Participativos\ndesconfiados (21.65%)",
                                                               "Poco\ncohesionados (67.46%)")))

save(tab_4_cs, file = "../input/data/tab_4_cs.RData")
save(renca_cs_lca, file = "../input/data/renca_cs_lca.RData")
```

