---
title: "Gráfico Presentación Renca"
author: "Cristóbal Ortiz"
output: html_document
date: "2023-07-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	fig.align = "left",
	fig.topcaption = TRUE,
	message = FALSE,
	warning = FALSE,
	cache = FALSE
)
Sys.setlocale("LC_ALL","ES_ES.UTF-8")
```

```{r packages, message=FALSE, warning=FALSE, include=FALSE}
library(poLCA)
library(knitr)
library(kableExtra)
library(gridExtra)
library(tidyverse)
library(sjmisc)
library(sjlabelled)
library(ggrepel)
library(ggalluvial)
library(haven)
```

```{r datos}
remove(list = ls())
renca <- read_dta("../input/data/Renca_1010_macrozona.dta")
#renca_1 <- read_dta("../input/data/Renca_320_unidadbarrial.dta")
load("../input/data/renca_cb_lca.Rdata")
load("../input/data/tab_4.Rdata")

```

```{r recode-renca}
renca <- renca %>% 
  filter(!q0039 %in% c(9,10),
         !q0048 %in% c(8,9),
         !q0039 %in% c(9,10))

renca <- renca %>% 
  mutate(sexo = as_label(q0034),
         edad = cut(as.numeric(renca$q0035),breaks=c(17,25,35,45,55,65,85),
                    labels=c("18-25","26-35","36-45","46-55","56-65", "66 o más")),
         educ = cut(q0039,breaks=c(1,3,5,8),
                    labels=c("Básica","Media","Profesional")),
         ingr  = factor(q0048, labels = c("Menos de $250.000","$250.000 - $350.000",
                                               "$350.000 - $450.000","$450.000 - $700.000",
                                               "$700.000 - $800.000","$900.000 - $1.00.0000",
                                               "Más de $1.000.000")))
renca_cb_lca <- renca_cb_lca %>% 
  left_join(renca, by = 'respondent_id') %>% 
  select(respondent_id, spbi, arra, soci, conf, part, apoy, sexo, edad, educ, ingr, class_4, q0001) %>% 
  drop_na()
```

# Cohesión barrial

```{r tipos-sexo}
renca_cb_lca %>%
  filter(!sexo == "Otro (especifique)") %>% 
  count(class_4, sexo) %>% 
  group_by(sexo) %>% 
  mutate(freq = (n/sum(n))) %>% 
  ggplot(aes(x = freq, y = fct_rev(sexo), fill = fct_rev(class_4), 
             label = scales::percent(ifelse(freq < .01, NA, freq), .1))) + 
  geom_bar(stat = 'identity', position = 'stack') +
  scale_x_continuous(labels = scales::percent) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5), 
            size = 3, na.rm = TRUE,) +
  theme_bw() + 
  scale_fill_viridis_d(end = .85, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),
        axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank()) +
  labs(y = NULL, x = NULL, fill = NULL,
       title = 'Perfiles de cohesión barrial según sexo')

```
```{r tipos-educ}
renca_cb_lca %>%
  count(class_4, educ) %>% 
  group_by(educ) %>% 
  mutate(freq = (n/sum(n))) %>% 
  ggplot(aes(x = freq, y = fct_rev(educ), fill = fct_rev(class_4), 
             label = scales::percent(ifelse(freq < .01, NA, freq), .1))) + 
  geom_bar(stat = 'identity', position = 'stack') +
  scale_x_continuous(labels = scales::percent) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5), 
            size = 3, na.rm = TRUE,) +
  theme_bw() + 
  scale_fill_viridis_d(end = .85, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),
        axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank()) +
  labs(y = NULL, x = NULL, fill = NULL,
       title = 'Perfiles de cohesión barrial según nivel educacional cursado')
```

```{r tipos-ingr}
renca_cb_lca %>%
  count(class_4, ingr) %>% 
  group_by(ingr) %>% 
  mutate(freq = (n/sum(n))) %>% 
  ggplot(aes(x = freq, y = fct_rev(ingr), fill = fct_rev(class_4), 
             label = scales::percent(ifelse(freq < .01, NA, freq), .1))) + 
  geom_bar(stat = 'identity', position = 'stack') +
  scale_x_continuous(labels = scales::percent) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5), 
            size = 3, na.rm = TRUE,) +
  theme_bw() + 
  scale_fill_viridis_d(end = .85, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),
        axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank()) +
  labs(y = NULL, x = NULL, fill = NULL,
       title = 'Perfiles de cohesión barrial según nivel de ingresos')
```

```{r tipos-zonas}
renca_cb_lca %>%
  as_label(q0001) %>% 
  count(class_4, q0001) %>% 
  group_by(q0001) %>% 
  mutate(freq = (n/sum(n))) %>% 
  ggplot(aes(x = freq, y = fct_rev(q0001), fill = fct_rev(class_4), 
             label = scales::percent(ifelse(freq < .01, NA, freq), .1))) + 
  geom_bar(stat = 'identity', position = 'stack') +
  scale_x_continuous(labels = scales::percent) +
  guides(fill = guide_legend(reverse = TRUE)) +
  geom_text(position = position_stack(vjust = .5), 
            size = 3, na.rm = TRUE,) +
  theme_bw() + 
  scale_fill_viridis_d(end = .85, direction = -1) +
  theme(plot.caption = element_text(hjust = 0),
        axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top',
        legend.title = element_blank()) +
  labs(y = NULL, x = NULL, fill = NULL,
       title = 'Perfiles de cohesión barrial según macrozona')
```

