---
title: "Clases Latentes Renca"
author: "Cristóbal Ortiz"
output: html_document
date: "2023-07-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	fig.align = "left",
	fig.topcaption = TRUE,
	message = FALSE,
	warning = FALSE,
	cache = FALSE
)
Sys.setlocale("LC_ALL","ES_ES.UTF-8")
```

```{r packages, message=FALSE, warning=FALSE, include=FALSE}
library(poLCA)
library(knitr)
library(kableExtra)
library(gridExtra)
library(tidyverse)
library(sjmisc)
library(sjlabelled)
library(ggrepel)
library(ggalluvial)
library(haven)
```

```{r datos}
remove(list = ls())
getwd()
renca <- read_dta("../1_input/data/Renca_1010_macrozona.dta")
```

```{r recode}
#remove(renca_part)

renca_part <- renca %>% 
  select(respondent_id, starts_with("q0009_"), -q0009_0016, -q0009_0017, -q0009_0018, -q0009_0019, -q0009_other) ##apoyo/visitas

renca_part <- renca_part %>% 
  mutate(junta_veci = replace(q0009_0001, is.na(q0009_0001), 2),
         comite_viv = replace(q0009_0002, is.na(q0009_0002), 2),
         club_depor = replace(q0009_0003, is.na(q0009_0003), 2),
         orga_relig = replace(q0009_0004, is.na(q0009_0004), 2),
         agrup_arte = replace(q0009_0005, is.na(q0009_0005), 2),
         grup_inden = replace(q0009_0006, is.na(q0009_0006), 2),
         grup_joven = replace(q0009_0007, is.na(q0009_0007), 2),
         grup_mujer = replace(q0009_0008, is.na(q0009_0008), 2),
         grup_adult = replace(q0009_0009, is.na(q0009_0009), 2),
         grup_volun = replace(q0009_0010, is.na(q0009_0010), 2),
         grup_salud = replace(q0009_0011, is.na(q0009_0011), 2),
         part_polit = replace(q0009_0012, is.na(q0009_0012), 2),
         grup_corpo = replace(q0009_0013, is.na(q0009_0013), 2),
         cent_apode = replace(q0009_0014, is.na(q0009_0014), 2),
         comite_seg = replace(q0009_0015, is.na(q0009_0015), 2)) %>% 
  set_labels(junta_veci, labels = c("Sí","No")) %>% 
  set_labels(comite_viv, labels = c("Sí","No")) %>% 
  set_labels(club_depor, labels = c("Sí","No")) %>% 
  set_labels(orga_relig, labels = c("Sí","No")) %>% 
  set_labels(agrup_arte, labels = c("Sí","No")) %>% 
  set_labels(grup_inden, labels = c("Sí","No")) %>% 
  set_labels(grup_joven, labels = c("Sí","No")) %>% 
  set_labels(grup_mujer, labels = c("Sí","No")) %>% 
  set_labels(grup_adult, labels = c("Sí","No")) %>% 
  set_labels(grup_volun, labels = c("Sí","No")) %>% 
  set_labels(grup_salud, labels = c("Sí","No")) %>% 
  set_labels(part_polit, labels = c("Sí","No")) %>% 
  set_labels(grup_corpo, labels = c("Sí","No")) %>% 
  set_labels(cent_apode, labels = c("Sí","No")) %>% 
  set_labels(comite_seg, labels = c("Sí","No")) %>%  
  as_numeric(junta_veci, comite_viv, club_depor, orga_relig, agrup_arte, grup_inden, 
             grup_joven, grup_mujer, grup_adult, grup_volun, grup_salud, part_polit, 
             grup_corpo, cent_apode, comite_seg) 

renca_part_lca <- renca_part %>% 
  select(respondent_id, junta_veci, comite_viv, club_depor, orga_relig, agrup_arte, grup_inden, 
             grup_joven, grup_mujer, grup_adult, grup_volun, grup_salud, part_polit, 
             grup_corpo, cent_apode, comite_seg) %>% 
  drop_na()
```

```{r modelo-lca}
set.seed(1)

var <- cbind(junta_veci, comite_viv, club_depor, orga_relig, agrup_arte, grup_inden, 
             grup_joven, grup_mujer, grup_adult, grup_volun, grup_salud, part_polit, 
             grup_corpo, cent_apode, comite_seg) ~ 1

# Tres clases --------------------------------------------------------------------------
#tipos_3 <- poLCA(var, renca_part_lca, nclass = 3, na.rm = TRUE, maxiter = 5000, nrep = 10)

#renca_part_lca$clase_3 <- as.factor(tipos_3$predclass)

#tabla_3 <- table(renca_part_lca$clase_3)
#prop.table(tabla_3)

# Cuatro clases ------------------------------------------------------------------------
tipos_4 <- poLCA(var, renca_part_lca, nclass = 4, na.rm = TRUE, maxiter = 5000, nrep = 10)

renca_part_lca$clase_4 <- as.factor(tipos_4$predclass)

tabla_4 <- table(renca_part_lca$clase_4)
prop.table(tabla_4)

# Cinco clases  ------------------------------------------------------------------------
#tipos_5 <- poLCA(var, renca_part_lca, nclass = 5, na.rm = TRUE, maxiter = 5000, nrep = 10)

#renca_part_lca$clase_5 <- as.factor(tipos_5$predclass)

#tabla_5 <- table(renca_part_lca$clase_5)
#prop.table(tabla_5)
```

```{r}
tab4_1 <- renca_part_lca %>% group_by(clase_4, junta_veci) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 1) %>% rename(Clase=clase_4, Tipos=junta_veci)

tab4_2 <- renca_part_lca %>% group_by(clase_4, comite_viv) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 2) %>% rename(Clase=clase_4, Tipos=comite_viv)

tab4_3 <- renca_part_lca %>% group_by(clase_4, club_depor) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 3) %>% rename(Clase=clase_4, Tipos=club_depor)

tab4_4 <- renca_part_lca %>% group_by(clase_4, orga_relig) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 4) %>% rename(Clase=clase_4, Tipos=orga_relig)

tab4_5 <- renca_part_lca %>% group_by(clase_4, agrup_arte) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 5) %>% rename(Clase=clase_4, Tipos=agrup_arte)

tab4_6 <- renca_part_lca %>% group_by(clase_4, grup_inden) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 6) %>% rename(Clase=clase_4, Tipos=grup_inden)

tab4_7 <- renca_part_lca %>% group_by(clase_4, grup_joven) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 7) %>% rename(Clase=clase_4, Tipos=grup_joven)

tab4_8 <- renca_part_lca %>% group_by(clase_4, grup_mujer) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 8) %>% rename(Clase=clase_4, Tipos=grup_mujer)

tab4_9 <- renca_part_lca %>% group_by(clase_4, grup_adult) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 9) %>% rename(Clase=clase_4, Tipos=grup_adult)

tab4_10 <- renca_part_lca %>% group_by(clase_4, grup_volun) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 10) %>% rename(Clase=clase_4, Tipos=grup_volun)

tab4_11 <- renca_part_lca %>% group_by(clase_4, grup_salud) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 11) %>% rename(Clase=clase_4, Tipos=grup_salud)

tab4_12 <- renca_part_lca %>% group_by(clase_4, part_polit) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 12) %>% rename(Clase=clase_4, Tipos=part_polit)

tab4_13 <- renca_part_lca %>% group_by(clase_4, grup_corpo) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 13) %>% rename(Clase=clase_4, Tipos=grup_corpo)

tab4_14 <- renca_part_lca %>% group_by(clase_4, cent_apode) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 14) %>% rename(Clase=clase_4, Tipos=cent_apode)

tab4_15 <- renca_part_lca %>% group_by(clase_4, comite_seg) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 15) %>% rename(Clase=clase_4, Tipos=comite_seg)


tab_4 <- rbind(tab4_1, tab4_2, tab4_3, tab4_4, tab4_5,
               tab4_6, tab4_7, tab4_8, tab4_9, tab4_10,
               tab4_11, tab4_12, tab4_13, tab4_14, tab4_15)

rm(tab4_1, tab4_2, tab4_3, tab4_4, tab4_5,
   tab4_6, tab4_7, tab4_8, tab4_9, tab4_10,
   tab4_11, tab4_12, tab4_13, tab4_14, tab4_15)
```

```{r cuatro-clases}


#   1     2     3     4 
# 0.25  0.24  0.27  0.24b  

tab_4 <- tab_4 %>% 
  mutate(Clase = factor(Clase, levels = c(1,2,3,4), labels = c("1", 
                                                               "2", 
                                                               "3",
                                                               "4")),
         Tipos  = factor(Tipos, levels = c(1,2), labels = c("Sí", "No")),
         var  = factor(var, levels = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15),
                       labels = c("JJVV",
                                  "Vivienda",
                                  "Deportivo",
                                  "Religioso",
                                  "Artístico",
                                  "Étnico",
                                  "Juvenil",
                                  "Mujeres",
                                  "Adulto mayor",
                                  "Voluntariado",
                                  "Salud",
                                  "Político",
                                  "Corporativo",
                                  "Apoderados",
                                  "Seguridad")))

tab_4 %>% ggplot(aes(x = freq, y = factor(var, levels = c("JJVV",
                                  "Vivienda",
                                  "Deportivo",
                                  "Religioso",
                                  "Artístico",
                                  "Étnico",
                                  "Juvenil",
                                  "Mujeres",
                                  "Adulto mayor",
                                  "Voluntariado",
                                  "Salud",
                                  "Político",
                                  "Corporativo",
                                  "Apoderados",
                                  "Seguridad")),  
                     fill = Tipos)) + 
  geom_bar(stat = 'identity', position = 'stack') +
  labs(y = NULL, x = NULL,
       title = "Perfiles de participación: 4 clases", fill = "En los últimos 12 meses\n¿ha participado en alguna de\nlas siguientes organizaciones?") +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 5), labels = scales::percent, limits=c(0, 1)) +
  theme_bw() + 
  scale_fill_viridis_d(end = .85, option = 'viridis', direction = -1) +
  theme(axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top') +
  facet_grid(~ Clase) +
  guides(fill = guide_legend(reverse = TRUE))

ggsave(filename = "../3_output/4_clases_part.jpg", width = 35, height = 15, units = "cm")
```

```{r save-dataset}
renca_part_lca <- renca_part_lca %>% 
  mutate(class_4 = factor(clase_4, levels = c(1,2,3,4), labels = c("Altamente\ncohesionados\n(23.25%)", 
                                                               "Apegados\ndesconfiados\n(29.23%)", 
                                                               "Desapegados\nrelacionales\n(22.57%)",
                                                               "Poco\ncohesionados\n(24.94%)")))

save(tab_4, file = "../input/data/tab_4.RData")
save(renca_part_lca, file = "../input/data/renca_part_lca.RData")
```

