---
title: "Clases Latentes Participación Cívica Renca"
author: "Cristóbal Ortiz"
output: html_document
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	fig.align = "left",
	fig.topcaption = TRUE,
	message = FALSE,
	warning = FALSE,
	cache = FALSE
)
Sys.setlocale("LC_ALL","ES_ES.UTF-8")
```

```{r packages, message=FALSE, warning=FALSE, include=FALSE}
library(poLCA)
library(knitr)
library(tidyverse)
library(sjmisc)
library(sjlabelled)
```

```{r datos}
remove(list = ls())
getwd()
renca_civic <- read_dta("../1_input/data/Renca_1010_macrozona.dta")
```

```{r recode}
#remove(renca_civic)

renca_civic <- renca_civic %>% 
  select(respondent_id, starts_with("q0011_"), q0009_0016) 

renca_civic <- renca_civic %>% 
  mutate(across(starts_with("q0011_"), ~if_else(. %in% 3:4, NA_real_, .)), #convierto a NA los NS/NR
         across(starts_with("q0011_"), ~car::recode(., "1=2; 2=1")), #recode para que "No" sea 1 y "Sí" sea 2
         reu_comunit = q0011_0001,
         firma_carta = q0011_0002,
         asis_marcha = q0011_0003,
         expres_rrss = q0011_0004,
         part_organi = if_else(q0009_0016 == 2, 1, q0009_0016)) %>% #recode para que "No" sea 1 
  mutate(part_organi = replace(part_organi, is.na(part_organi), 2)) %>% #recode para que NA sea 2 y "Sí"
  set_labels(part_organi, reu_comunit, firma_carta, asis_marcha, expres_rrss, labels = c("No", "Sí")) %>% 
  as_numeric(part_organi, reu_comunit, firma_carta, asis_marcha, expres_rrss) 

renca_civic_lca <- renca_civic %>% 
  select(respondent_id, part_organi, reu_comunit, firma_carta, asis_marcha, expres_rrss) %>% 
  drop_na()
```

```{r lca-3}
set.seed(1)

# Especifico variables
var_name <- c("part_organi", "reu_comunit", "firma_carta", "asis_marcha", "expres_rrss")
var_label <- c("Organizaciones", "Reuniones", "Firma de carta", "Asiste marcha", "Opina en RRSS")
var_lca <- cbind(part_organi, reu_comunit, firma_carta, asis_marcha, expres_rrss) ~ 1

# Tres clases --------------------------------------------------------------------------
lca_3 <- poLCA(var_lca, renca_civic_lca, nclass = 3, na.rm = TRUE, maxiter = 5000, nrep = 10) #modelo de clases latentes
renca_civic_lca$clase_3 <- as.factor(lca_3$predclass) #variable de clases predichas
```

## Tres clases

```{r tabla-3}
tab_3 <- renca_civic_lca %>%
  pivot_longer(cols = all_of(var_name)) %>%
  group_by(clase_3, name, value) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n),
         var_lca = as.numeric(factor(name, levels = var_name))) %>%
  ungroup() %>%
  mutate(clase_3 = factor(clase_3, levels = 1:3, labels = paste0(round(prop.table(table(renca_civic_lca$clase_3)) * 100, 1), "%")),
         value = factor(value, levels = 1:2, labels = c("No", "Sí")),
         var_lca = factor(var_lca, levels = 1:5, labels = var_label))
```

```{r plot-3}
tab_3 %>%
  ggplot(aes(x = freq, 
             y = factor(var_lca, levels = rev(var_label)),  
             fill = value)) + 
  geom_bar(stat = 'identity', position = 'stack') +
  labs(y = NULL, x = NULL,
       title = "Perfiles de participación social: 3 clases latentes", 
       fill = "En los últimos 12 meses ¿ha participado\nen alguna de las siguientes instancias?") +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 5), labels = scales::percent, limits=c(0,1)) +
  theme_bw() + 
  scale_fill_viridis_d(end = .85, option = 'viridis') +
  theme(axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top') +
  facet_grid(~ clase_3) +
  guides(fill = guide_legend(reverse = TRUE))

ggsave(filename = "../3_output/3_clases_part.jpg", width = 35, height = 15, units = "cm")
```

```{r save-3}
renca_civic_lca <- renca_civic_lca %>% 
  mutate(clase_3_label = factor(clase_3, levels = 1:3, 
                                labels = c(paste0("Clase 1", " (", round(prop.table(table(renca_civic_lca$clase_3)) * 100, 1)[1], "%)"), 
                                           paste0("Clase 2", " (", round(prop.table(table(renca_civic_lca$clase_3)) * 100, 1)[2], "%)"),
                                           paste0("Clase 3", " (", round(prop.table(table(renca_civic_lca$clase_3)) * 100, 1)[3], "%)"))))

save(renca_civic_lca, file = "../1_input/data/procesada/renca_civic_lca.RData")
```

## Cuatro clases (obsoleto)

```{r lca-4}
# Cuatro clases ------------------------------------------------------------------------
tipos_4 <- poLCA(var_lca, renca_civic_lca, nclass = 4, na.rm = TRUE, maxiter = 5000, nrep = 10)

renca_civic_lca$clase_4 <- as.factor(tipos_4$predclass)

tabla_4 <- table(renca_civic_lca$clase_4)
```

```{r tabla-4}
#part_organi, reu_comunit, firma_carta, asis_marcha, expres_rrss

tab4_1 <- renca_civic_lca %>% group_by(clase_4, part_organi) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 1) %>% rename(Clase=clase_4, Tipos=part_organi)

tab4_2 <- renca_civic_lca %>% group_by(clase_4, reu_comunit) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 2) %>% rename(Clase=clase_4, Tipos=reu_comunit)

tab4_3 <- renca_civic_lca %>% group_by(clase_4, firma_carta) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 3) %>% rename(Clase=clase_4, Tipos=firma_carta)

tab4_4 <- renca_civic_lca %>% group_by(clase_4, asis_marcha) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 4) %>% rename(Clase=clase_4, Tipos=asis_marcha)

tab4_5 <- renca_civic_lca %>% group_by(clase_4, expres_rrss) %>%
  summarise (n = n()) %>% mutate(freq = n / sum(n)) %>% 
  mutate(var = 5) %>% rename(Clase=clase_4, Tipos=expres_rrss)

tab_4 <- rbind(tab4_1, tab4_2, tab4_3, tab4_4, tab4_5)

rm(tab4_1, tab4_2, tab4_3, tab4_4, tab4_5)
```

```{r plot-4}
tab_4 <- tab_4 %>% 
  mutate(Clase = factor(Clase, levels = c(1,2,3,4), 
                        labels = c(paste0(round(prop.table(tabla_4)*100, 1)[1],"%"),
                                   paste0(round(prop.table(tabla_4)*100, 1)[2],"%"),
                                   paste0(round(prop.table(tabla_4)*100, 1)[3],"%"),
                                   paste0(round(prop.table(tabla_4)*100, 1)[4],"%"))),
         Tipos  = factor(Tipos, levels = c(1,2), 
                         labels = c("No","Sí")),
         var  = factor(var, levels = c(1,2,3,4,5),
                       labels = c("Organizaciones",
                                  "Reuniones",
                                  "Firma de carta",
                                  "Asiste marcha",
                                  "Opina en RRSS")))

tab_4 %>% ggplot(aes(x = freq, 
                     y = factor(var, levels = c("Opina en RRSS",
                                                "Asiste marcha",
                                                "Firma de carta",
                                                "Reuniones",
                                                "Organizaciones")),  
                     fill = Tipos)) + 
  geom_bar(stat = 'identity', position = 'stack') +
  labs(y = NULL, x = NULL,
       title = "Perfiles de participación social: 4 clases latentes", fill = "En los últimos 12 meses ¿ha participado\nen alguna de las siguientes instancias?") +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 5), labels = scales::percent, limits=c(0, 1)) +
  theme_bw() + 
  scale_fill_viridis_d(end = .85, option = 'viridis') +
  theme(axis.text.x = element_text(size = rel(.9)),
        legend.position = 'top') +
  facet_grid(~ Clase) +
  guides(fill = guide_legend(reverse = TRUE))

ggsave(filename = "../3_output/4_clases_part.jpg", width = 35, height = 15, units = "cm")
```

```{r save-4}
renca_civic_lca <- renca_civic_lca %>% 
  mutate(class_4 = factor(clase_4, levels = c(1,2,3,4), labels = c("Altamente\ncohesionados\n(23.25%)", 
                                                               "Apegados\ndesconfiados\n(29.23%)", 
                                                               "Desapegados\nrelacionales\n(22.57%)",
                                                               "Poco\ncohesionados\n(24.94%)")))

save(tab_4, file = "../input/data/tab_4.RData")
save(renca_civic_lca, file = "../input/data/renca_civic_lca.RData")
```

